Repository cloud-native-toolkit/terraform-k8s-ocp-cluster, pull requests merged in 2020-08, with the labels that each got.

#6 add output for hostname
  outputs.tf
Labels: chore, minor

#7 Updates configuration to use common helm chart
  .github/workflows/verify.yaml
  chart/cloud-setup/.helmignore
  chart/cloud-setup/Chart.lock
  chart/cloud-setup/Chart.yaml
  chart/cloud-setup/charts/cloud-setup-0.2.1.tgz
  chart/cloud-setup/templates/.gitkeep
  chart/cloud-setup/values.yaml
  main.tf
  variables.tf
Labels: feature, minor

#8 Fixes output dependencies to renamed helm_release resource
  .github/workflows/verify.yaml
  outputs.tf
Labels: bug, patch

#9 Outputs tls_secret_name with hard-coded value to fix tool logic
  outputs.tf
Labels: bug, patch
